config/routes.rb
Keypunch::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :groups, :except => [ :destroy ] do
    resources :entities, only: [:new, :create]
  end

  #resources :entities, :except => [ :destroy ] do
  resources :entities do
    member do
      get 'show_password'
    end
  end
  resource :home, :only => [ :index ]
  resources :keepass, only:  [ :index, :new, :create ]
  resources :users, except: [:new, :create, :destroy]

  root :to => 'home#index'
end

app/views/layouts/shared/app_nav_mobile.html.erb
<div class="row">
  <div class="twelve columns">
    <dl class="nice tabs mobile show-on-phones">
      <dd><%= link_to "Search", entities_path, :class => "#{is_current_nav?('passwords')}" %></dd>
        <% if current_user && current_user.role?(:admin) -%>
        <dd><%= link_to "Groups", groups_path, :class => "#{is_current_nav?('groups')}" %></dd>
        <dd><%= link_to "Users", users_path, :class => "#{is_current_nav?('users')}" %></dd>
        <dd><%= link_to "Import", new_keepas_path, :class => "#{is_current_nav?('keepass')}" %></dd>
      <% end %>
    </dl>
  </div>
</div>

app/views/layouts/shared/app_nav_top.html.erb
<div class="row">
  <div class="twelve columns">
    <dl class="nice tabs mobile hide-on-phones">
      <dd><%= link_to "Search", entities_path, :class => "#{is_current_nav?('passwords')}" %></dd>
        <% if current_user && current_user.role?(:admin) -%>
        <dd><%= link_to "Groups", groups_path, :class => "#{is_current_nav?('groups')}" %></dd>
        <dd><%= link_to "Users", users_path, :class => "#{is_current_nav?('users')}" %></dd>
        <dd><%= link_to "Import", new_keepas_path, :class => "#{is_current_nav?('keepass')}" %></dd>
      <% end %>
    </dl>
  </div>
</div>

app/views/layouts/shared/flashes.html.erb
<div class="row">
  <div class="twelve columns">
<%- if !flash.empty? or content_for?(:errors) -%>
    <%- %w(alert success notice error warning).each do |name| -%>
      <%- if flash[name.to_sym] -%>
        <%- if 'notice' == name
              css_class = 'success'
            elsif 'alert' == name
              css_class = 'error'
            else
              css_class = name
            end -%>
            <div class="alert-box <%= css_class %>">
              <%= flash[name.to_sym] %>
              <%= link_to 'x', '#', :class => 'close' %>
            </div>
        <% flash[name.to_sym] = nil %>
      <%- end -%>
    <%- end -%>
    <%= yield :errors %>
  <%- end -%>
  </div>
</div>

app/views/layouts/shared/foot.html.erb
    <!-- Das Footer -->
    <footer class="row">
      <section class="two columns">
        <h6><strong>Keypunch</strong></h6>
      </section>
      <section class="ten columns">
        <p>A group password management application made by <a href="http://domain7.com/">Domain7</a> Copyright &copy; <%= Time.now.year %></p>
      </section>
    </footer>
    <!-- /Das Footer -->
  </div>
</body>
</html>

app/views/layouts/shared/head.html.erb
<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <meta name="description" content="Foundation is an easy to use, powerful, and flexible framework for building rapid prototypes and production code on any kind of device." />

  <title>Keypunch beta</title>
  <!-- link rel="apple-touch-icon" href="../../apple-touch-icon.png" />
  <link rel="icon" type="image/ico" href="../../favicon.ico" -->

  <!-- Included CSS Files -->
  <link rel="stylesheet" href="/stylesheets/globals.css" />
  <link rel="stylesheet" href="/stylesheets/typography.css" />
  <link rel="stylesheet" href="/stylesheets/grid.css" />
  <link rel="stylesheet" href="/stylesheets/ui.css" />
  <link rel="stylesheet" href="/stylesheets/forms.css" />
  <link rel="stylesheet" href="/stylesheets/orbit.css" />
  <link rel="stylesheet" href="/stylesheets/reveal.css" />
  <link rel="stylesheet" href="/stylesheets/app.css" />
  <link rel="stylesheet" href="/stylesheets/chosen.css" />
  <link rel="stylesheet" href="/stylesheets/mobile.css" />
  <link rel="stylesheet" href="/simpletree/css/jquery-simpleTreeMenu-1.3.0.css" />
  <link rel="stylesheet" href="/stylesheets/presentation.css" />

  <!--[if lt IE 9]>
    <link rel="stylesheet" href="/stylesheets/ie.css" />
  <![endif]-->

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <script src="/javascripts/jquery.min.js"></script>
  <script src="/javascripts/jquery.reveal.js"></script>
  <script src="/javascripts/jquery.orbit-1.3.0.js"></script>
  <script src="/javascripts/forms.jquery.js"></script>
  <script src="/javascripts/jquery.customforms.js"></script>
  <script src="/javascripts/jquery.placeholder.min.js"></script>
  <script src="/javascripts/chosen.jquery.min.js"></script>
  <script src="/javascripts/app.js"></script>
  <script src="/javascripts/application.js"></script>
  <script src="/simpletree/js/jquery-simpleTreeMenu-1.3.0.js"></script>
  <script src="/javascripts/presentation.js"></script>
  <script>
    $(document).ready(function() {
      $('.tree').simpleTreeMenu();
    });
  </script>
  <%= yield :head_javascript %>
</head>

app/views/layouts/shared/top_nav.html.erb
<body id="-page" class="">

  <!-- ZURBar -->
  <div id="zurBar" class="container">
    <div class="row">
      <div class="four columns">
        <h1><%= link_to "Keypunch", root_path %></h1>
      </div>
      <% if current_user %>
      <div class="eight columns">
        <strong class="right">
          <%= link_to "Logout", logout_path, :class => "nice small blue radius button" %>
        </strong>
      </div>
      <% end %>
    </div>
  </div>
  <!-- /ZURBar -->
  <div class="container">