config/routes.rb
Keypunch::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :groups, :except => [ :destroy ] do
    resources :entities, only: [:new, :create]
  end

  #resources :entities, :except => [ :destroy ] do
  resources :entities do
    member do
      get 'show_password'
    end
  end
  resource :home, :only => [ :index ]
  resources :keepass, only:  [ :index, :new, :create ]
  resources :users, except: [:new, :create, :destroy]

  root :to => 'home#index'
end

app/models/entity.rb
class Entity < ActiveRecord::Base
  has_paper_trail skip: [:password]

  attr_accessible :group_ids, :name, :username, :password, :password_confirmation, :description, :protocol, :domain, :expire_at, :role_ids, :user_ids
  has_many :entity_groups
  has_many :entity_roles
  has_many :entity_users
  has_many :groups, :through => :entity_groups, :dependent => :destroy
  has_many :roles, :through => :entity_roles, :dependent => :destroy
  has_many :users, :through => :entity_users, :dependent => :destroy

  validates :name, :presence => true
  validates :username, :presence => true
  validates :password, :presence => true, :confirmation => true, :if => :password_changed?

  after_validation :set_password_changed_at

  after_save :default_role

  def self.search(search)
    entities = self
    if search
      group_ids = Group.where("title ~* ?",search).map { |g| g.id }
      entity_ids = EntityGroup.where(:group_id => group_ids).map { |e| e.entity_id }
      entities = entities.where("entities.name ~* ? OR entities.username ~* ? OR entities.description ~* ? OR entities.domain ~* ? OR entities.id IN (?)",
                                search, search, search, search, entity_ids)
    end
    entities
  end

  def self.load_keepass(file)
    require 'xml'
    doc = XML::Parser.file( file ).parse
    @entry_elements = %w[title username password url comment icon creation lastaccess lastmod expire]
    transaction do
      doc.root.children.each do |n|
        self.group_parse(nil, n) if n.name == 'group'
      end
    end
  end

  def domain_linkable?
    nil != URI::regexp(%w(http https)).match(self.domain)
  end

  def decrypt
    key_path = Rails.root.join('pgp')
    temp_file = Tempfile.new('message')
    temp_file.print(self.password)
    temp_file.flush
    `gpg --homedir #{key_path.to_s} -d #{temp_file.path}`
  end

  def role?(role)
    roles.map { |r| r.name }.include? role.to_s
  end

  def roles_include?(test_roles)
    test_role_ids = test_roles.map { |r| r.id.to_i }
    entity_role_ids = self.roles.map { |r| r.id.to_i }
    (test_role_ids & entity_role_ids).size > 0
  end

  def display_roles
    self.roles.map{ |r| r.name }.join(', ')
  end

  def user?(user)
    users.map { |u| u.id.to_i}.include? user.id.to_i
  end

  def display_users
    self.users.map{ |u| u.email }.join(', ')
  end

  private
    def self.group_parse(pid,node)
      title = node.find('title').first.content
      if pid.nil?
        gid = Group.find_or_create_by_title_and_ancestry(title, nil).id
      else
        ancestry = Group.find_by_id(pid).path_ids.join('/')
        gid = Group.find_or_create_by_title_and_ancestry(title, ancestry).id
      end

      node.children.each do |n|
        self.group_parse(gid, n) if n.name == 'group'
        self.entry_parse(gid, n) if n.name == 'entry'
      end
    end

    def self.entry_parse(gid,node)
      tmp = {}
      @entry_elements.each do |fname|
        tmp[fname.intern] = node.find(fname).first.content
      end
      current_entity = self.find_by_group_id_and_name(gid,tmp[:title])
      if current_entity
        current_entity.update_attributes( :group_id => gid, :name => tmp[:title], :username => tmp[:username], :password => tmp[:password], :description => tmp[:comment], :domain => tmp[:url], :expire_at => tmp[:expire], :created_at  => tmp[:creation], :updated_at => tmp[:lastmod])
      else
        self.create( :group_id => gid, :name => tmp[:title], :username => tmp[:username], :password => tmp[:password], :description => tmp[:comment], :domain => tmp[:url], :expire_at => tmp[:expire], :created_at  => tmp[:creation], :updated_at => tmp[:lastmod])
      end
    end

    def password_changed?
      if ! self.new_record?
        ! self.password.blank?
      else
        return true
      end
    end

    def default_role
      self.roles << Role.find_or_create_by(name: 'Public') if self.roles.empty? && self.users.empty?  #TODO: add check for private when this is implemented
    end

    def set_password_changed_at
      if !self.new_record? && password_changed?
        self.password_changed_at = Time.zone.now
      end
    end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  load_and_authorize_resource
  before_filter :admin_only, :only => :destroy
  before_filter :find_group, only: [:new]
  before_filter { |controller| controller.set_current_nav('passwords') }

  helper_method :sort_order,:sort_column,:sort_direction
  layout 'entities'

  def show_password
    entity = Entity.find(params[:id])
    authorize! :edit, entity
    # this one's for you, shane
    pyoksok = entity.decrypt

    respond_to do |format|
      format.json { render :json => pyoksok.to_json }
    end
  end

  def index
    s = params[:search_phrase]
    @entities = Entity
      .search(s)
      .includes([:entity_roles,:entity_users,:groups])
      .where('entity_roles.role_id IN (?) OR entity_users.user_id = ?', current_user.roles.map{|x| x.id}, current_user.id)
      .order(sort_order)
      .paginate(:page => params[:page], :per_page => 50)

  end

  def show
    @entity = Entity.find(params[:id])
    @versions = @entity.versions.limit(10).reverse
  end

  def new
    if @group
      @entity = Entity.new(:group_ids => [@group.id])
    else
      @entity = Entity.new
    end

    @group_options = Group.all
  end

  def create
    @entity = Entity.new(params[:entity])

    respond_to do |format|
      if @entity.save
        format.html { redirect_to @entity, notice: 'Password was successfully created.' }
      else
        @group_options = Group.all
        flash[:error] = @entity.errors.full_messages.join('<br />')
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @entity = Entity.find(params[:id])
    @group_options = Group.all
  end

  def update
    @entity = Entity.find(params[:id])

    if params[:entity][:password].blank?
      params[:entity].delete('password')
      params[:entity].delete('password_confirmation')
    end

    respond_to do |format|
      if @entity.update_attributes(:entity => params[:entity])
        format.html { redirect_to @entity, notice: 'Password was successfully updated.' }
      else
        @group_options = Group.all
        flash[:error] = @entity.errors.full_messages.join('<br />')
        format.html { render action: "edit" }
      end
    end
  end

  def destroy
    @entity = Entity.find(params[:id])
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_path, notice: 'Password was successfully deleted.' }
    end
  end

  private

  def find_group
    g = Group.find_by_id params[:group_id]
    if g and g.is_childless?
      @group = g
    end
  end

  def sort_column
    params[:sort] || "entities.name, entities.created_at"
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_actions.html.erb
<div class="panel">
  <p>
    <% if @group and @group.is_childless? %>
        <%= link_to("New Password", new_group_entity_path(@group), :class => "nice radius blue button mobile") %>
    <% else %>
        <%= link_to("New Password", new_entity_path, :class => "nice radius blue button mobile") %>
    <% end %>
  </p>
</div>
<% if current_user.role?('admin') && @group && @group.id %>
<div class="panel">
  <p>
    <%= link_to("New Group", new_group_path(:group_id => @group.id), :class => "nice radius blue button mobile") %>
  </p>
  <p>
    <%= link_to("Edit Group", edit_group_path(@group), :class => "nice radius blue button mobile") %>
  </p>
</div>
<% end %>

app/views/entities/_edit_actions.html.erb
<div class="panel">
  <p>
    <% if @entity.id %>
      <%= link_to("Cancel", entity_path(@entity), :class => "nice radius white button mobile") %>
    <% elsif @group %>
      <%= link_to("Cancel", group_path(@group.id), :class => "nice radius white button mobile") %>
    <% else %>
      <%= link_to("Cancel", entities_path, :class => "nice radius white button mobile") %>
    <% end %>
  </p>
</div>

app/views/entities/_form.html.erb
<% content_for :head_javascript do %>
  <%= javascript_include_tag("/javascripts/jquery.pwdstr.js") %>
  <%= javascript_tag do -%>
    $(document).ready(function() {
        $('#entity_password').pwdstr('#timehack');
        $(".chzn-select").chosen();
    });
  <% end -%>
<% end %>

<%= form_for @entity, :html => { :class => 'nice' } do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name, :class => 'input-text' %>
  <%= f.label :group_ids, "Groups" %>
  <%= f.select(:group_ids,
    options_for_select(@group_options.collect { |i| [i.title, i.id] }, @entity.group_ids),
    { :id => "entity_group_ids", :name => "group[group_ids][]" },
    { :multiple => true, :size => 6, :class => "chzn-select" } ) 
  %>
  <%= f.label :username, "Username" %>
  <%= f.text_field :username, :class => 'input-text' %>
  <%= f.label :password, "Password" %>
  <%= f.password_field :password, :class => 'input-text' %>
  <%= f.label :password_confirmation, "Password confirmation" %>
  <%= f.password_field :password_confirmation, :class => 'input-text' %>
  <p id="hacktip">Time to bruteforce this password:<span id="timehack">None</span></p>
  <%= f.label :description, "Description" %>
  <%= f.text_area :description, :class => 'input-text', :rows => '8' %>
  <%= f.label :protocol, "Protocol" %>
  <%= f.text_field :protocol, :class => 'input-text' %>
  <%= f.label :domain, "URL" %>
  <%= f.text_field :domain, :class => 'input-text' %>
  <% if @current_user.role?('admin') %>
    <%= f.label :role_ids, "Roles" %>
    <%= f.select(:role_ids, options_for_select(Role.all.collect { |i| [i.name, i.id] }, @entity.role_ids), { :id => "entity_role_ids", :name => "role[role_ids][]" }, { :multiple => true, :size => 6, :class => "chzn-select" } ) %>
    <%= f.label :user_ids, "Users" %>
    <%= f.select(:user_ids, options_for_select(User.all.collect { |i| [i.email, i.id] }, @entity.user_ids), { :id => "entity_user_ids", :name => "user[user_ids][]" }, { :multiple => true, :size => 6, :class => "chzn-select" } ) %>
  <% end  %>
  <%= f.submit "Save", 'data-disable-with' => 'Saving...', :class => 'nice large blue radius button' %>
<% end %>

app/views/entities/_search_form.html.erb
<div class="panel">
  <%= form_tag(entities_path, :method => :get, :class => "nice", :id => "search") do %>
    <label for="search_phrase">Search</label>
    <%= text_field_tag(:search_phrase, params[:search_phrase], :class => "input-text value") %> 
    <%= submit_tag "Search", :name => nil, :class => "nice small blue radius button" %>  
  <% end %> 
</div>

app/views/entities/_show_actions.html.erb
<div class="panel">
  <p>
    <%= link_to("Edit", edit_entity_path(@entity), :class => "nice radius blue button mobile") %>
  </p>
    <% if current_user.role?('admin') -%>
      <%= button_to("Delete", entity_path, :method => :delete, :class => "nice radius red button mobile") %>
    <% end -%>
</div>

app/views/entities/edit.html.erb
<% content_for :side_column do %>
  <%= render :partial => "entities/edit_actions" %>
<% end %>

<h1><%= title @entity.name %></h1>
<hr />
<div class="panel">
  <%= render :partial => 'form' %>
</div>

app/views/entities/index.html.erb
<% content_for :side_column do %>
  <%= render :partial => "entities/actions" %>
  <%= render :partial => "groups/group_tree" %>
<% end %>

<%= render :partial => "entities/search_form" %>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<p><%=raw page_entries_info @entities %></p>
<table id="entities" class="zebra-striped">
  <thead>
    <th class="blue header"><%= sortable('entities.name','Name') %></th>
    <th class="blue header">Group</th>
  </thead>
  <tbody>
    <% @entities.each do |e| %>
      <tr id="<%= dom_id(e) %>">
        <td><%= link_to(e.name, entity_path(e)) %></td>
        <td>
          <% e.groups.each do |group| %>
            <div><%= link_to(group.title, group_path(group)) %></div>
          <% end %>
         </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/entities/new.html.erb
<% content_for :side_column do %>
  <%= render :partial => "entities/edit_actions" %>
<% end %>

<h1><%= title "New Password" %></h1>
<hr />

<div class="panel">
  <%= render :partial => 'form' %>
</div>

app/views/entities/show.html.erb
<% content_for :side_column do %>
  <%= render :partial => "entities/show_actions" %>
<% end %>

<% content_for :head_javascript do %>
  <%= javascript_tag do -%>
    var e_path = '<%= show_password_entity_path(@entity) %>';
  <% end -%>
  <%= javascript_include_tag("/javascripts/entity_show") %>
<% end %>

<h1><%= title @entity.name %></h1>
<hr />

<p><strong>Groups:</strong></p>
<ul id="group_list">
<% @entity.groups.each do |group| %>
  <li id="group_<%= dom_id(group) %>"><%= link_to(group.title, group_path(group)) %></li>
<% end %>
</ul>

<table id="entity_<%= dom_id(@entity) %>" class="entry">
  <tbody><tr>
      <td>Username</td>
      <td><%= @entity.username %></td>
    </tr>
    <tr>
      <td>Password</td>
      <td><input type="text" id="cpasswd" value="****************" readonly="readonly" /> <a href="#" id="get_passwd" class="small nice black button radius">Show</a>
    </tr>
    <tr>
      <td>Description</td>
      <td><pre><%= @entity.description %></pre></td>
    </tr>
    <tr>
      <td>Protocol</td>
      <td><%= @entity.protocol %></td>
    </tr>
    <tr>
      <td>Domain</td>
      <td>
      <%- if @entity.domain_linkable? %>
        <%= link_to(@entity.domain, @entity.domain, :target =>'_blank') %>
      <%- else%>
        <%= @entity.domain %>
      <%- end%>
      </td>
    </tr>
    <tr>
      <td>Expires</td>
      <td><%= @entity.expire_at %></td>
    </tr>
    <tr>
      <td>Created</td>
      <td><%= @entity.created_at %></td>
    </tr>
    <tr>
      <td>Modified</td>
      <td><%= @entity.updated_at %></td>
    </tr>
<% if @current_user.role?('admin') %>
    <tr>
      <td>Roles</td>
      <td id="role_ids"><%= @entity.display_roles %></td>
    </tr>
    <tr>
      <td>Users</td>
      <td id="user_ids"><%= @entity.display_users %></td>
    </tr>
<% end %>
  </tbody>
</table>

<% if @current_user.role?('admin') && @versions && @versions.count > 0 %>
  <h3>Changes</h3>
  <table id="<%= dom_id(@entity) %>_versions" class="entry">
    <thead>
      <tr>
        <th>Date</th>
        <th>Event</th>
        <th>Who</th>
        <th>Changes</th>
      </tr>
    </thead>
    <tbody>
      <% @versions.each do |e| %>
        <tr id="<%= dom_id(e) %>">
          <td><%= e.created_at %></td>
          <td><%= e.event %></td>
          <td><%= User.find(e.whodunnit).email if e.whodunnit and User.find_by_id(e.whodunnit) %></td>
          <td><%= e.changeset %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>