config/routes.rb
Keypunch::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :user do
    get 'logout' => 'devise/sessions#destroy'
    get 'login' => 'devise/sessions#new'
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  resources :groups, :except => [ :destroy ] do
    resources :entities, only: [:new, :create]
  end

  #resources :entities, :except => [ :destroy ] do
  resources :entities do
    member do
      get 'show_password'
    end
  end
  resource :home, :only => [ :index ]
  resources :keepass, only:  [ :index, :new, :create ]
  resources :users, except: [:new, :create, :destroy]

  root :to => 'home#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :recoverable, :trackable, :validatable, :lockable, :timeoutable, :omniauthable
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name
  attr_accessible :role_ids, :first_name, :last_name, :as => :admin

  validates :password, :password_strength => true, :password_unique => true
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_many :password_histories, :dependent => :destroy, :as => :uniqueable

  after_save :store_digest
  after_save :default_role

  def self.find_for_googleapps_oauth(access_token, signed_in_resource=nil)
    data = access_token['info']
    if user = User.find_by_email(data['email'])
      user
    else #create a user with stub pwd
      #NOTE: make sure password validation rules pass one uppper,lower,number,punctuation Pp!1
      User.create!(:email => data['email'], :password => Devise.friendly_token[0,20] + 'Pp!1' )
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.googleapps_data'] && session['devise.googleapps_data']['user_info']
        user.email = data['email']
      end
    end
  end

  def role?(role)
    roles.map { |r| r.name }.include? role.to_s
  end

  def full_name
    [self.first_name, self.last_name].join(" ")
  end

  def display_roles
    self.roles.map{ |r| r.name }.join(', ')
  end

  def store_digest
    if encrypted_password_changed?
      PasswordHistory.create(:uniqueable => self, :encrypted_password => encrypted_password)
    end
  end

  def default_role
    self.roles << Role.find_or_create_by(name: 'Public') if self.roles.empty?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  protect_from_forgery :except => :google_apps

  def google_apps
    @user = User.find_for_googleapps_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      flash[:success] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google Apps"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.googleapps_data"] = request.env["omniauth.auth"]
      redirect_to_new_user_registration_url
    end
  end

  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_only
  before_filter { |controller| controller.set_current_nav('users') }

  layout 'entities'

  def index
    @users = User.paginate(:page => params[:page], :per_page => 50)
  end

  def show
    @user = User.find params[:id]
  end

  def edit
    @roles = Role.all
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    unless params[:user][:password].blank?
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]
      params[:user].delete('password')
      params[:user].delete('password_confirmation')
    end

    respond_to do |format|
      if @user.update_attributes(:user => params[:user], :as => :admin)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
      else
        flash[:error] = @user.errors.full_messages.join('<br />')
        @roles = Role.all
        format.html { render action: "edit" }
      end
    end
  end

end

app/views/users/_form.html.erb
<% content_for :head_javascript do %>
  <%= javascript_include_tag("/javascripts/jquery.pwdstr.js") %>
  <%= javascript_tag do -%>
    $(document).ready(function() {
        $('#user_password').pwdstr('#timehack');
        $(".chzn-select").chosen();
    });
  <% end -%>
<% end %>
<%= form_for @user, :html => { :class => 'nice' } do |f| %>
  <%= f.label :first_name, "First name" %>
  <%= f.text_field :first_name, :class => 'input-text' %>
  <%= f.label :last_name, "Last name" %>
  <%= f.text_field :last_name, :class => 'input-text' %>
  <%= f.label :role_ids, "Roles" %>
  <%= f.select(:role_ids, options_for_select(@roles.collect { |i| [i.name, i.id] }, @user.role_ids), { :id => "user_role_ids", :name => "role[role_ids][]" }, { :multiple => true, :size => 6, :class => "chzn-select" } ) %>
  <%= f.label :password, "Password" %>
  <%= f.password_field :password, :class => 'input-text' %>
  <%= f.label :password_confirmation, "Password confirmation" %>
  <%= f.password_field :password_confirmation, :class => 'input-text' %>
  <p id="hacktip">Time to bruteforce this password:<span id="timehack">None</span></p>

  <%= f.submit "Save", 'data-disable-with' => 'Saving...', :class => 'nice large blue radius button' %>
<% end %>

app/views/users/_show_actions.html.erb
<div class="panel">
  <p>
    <%= link_to("Edit", edit_user_path(@user), :class => "nice radius blue button mobile") %>
  </p>
</div>

app/views/users/edit.html.erb
<% content_for :side_column do %>
  <%#= render :partial => "entities/edit_actions" %>
<% end %>

<p>
  <strong>Email:</strong> <%= @user.email %>
</p>

<div class="panel">
  <%= render :partial => 'form' %>
</div>

app/views/users/index.html.erb
<% content_for :side_column do %>
<% end %>

<p><%=raw page_entries_info @users %></p>
<table id="users" class="zebra-striped">
  <thead>
    <th class="blue header">Email</th>
    <th class="blue header">Name</th>
  </thead>
  <tbody>
    <% @users.each do |e| %>
      <tr id="<%= dom_id(e) %>">
        <td><%= link_to(e.email, user_path(e)) %></td>
        <td><%= e.full_name %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @users, :inner_window => 2 %>

app/views/users/show.html.erb
<% content_for :side_column do %>
  <%= render :partial => "users/show_actions" %>
<% end %>

<h1><%= title @user.email%></h1>
<hr />

<table id="<%= dom_id(@user) %>" class="entry">
  <tbody>
    <tr>
      <td>Email</td>
      <td><%= @user.email %></td>
    </tr>
    <tr>
      <td>Roles</td>
      <td id="role_ids"><%= @user.display_roles %></td>
    </tr>
    <tr>
      <td>Name</td>
      <td><%= @user.full_name %></td>
    </tr>
    <tr>
      <td>Sign In Count</td>
      <td><%= @user.sign_in_count %></td>
    </tr>
    <tr>
      <td>Current Sign In At</td>
      <td><%= @user.current_sign_in_at %></td>
    </tr>
    <tr>
      <td>Last Sign In At</td>
      <td><%= @user.last_sign_in_at %></td>
    </tr>
    <tr>
      <td>Last Sign In IP</td>
      <td><%= @user.last_sign_in_ip %></td>
    </tr>
    <tr>
      <td>Failed Attempts</td>
      <td><%= @user.failed_attempts %></td>
    </tr>
    <tr>
      <td>Locked At</td>
      <td><%= @user.locked_at %></td>
    </tr>
    <tr>
      <td>Created At</td>
      <td><%= @user.created_at %></td>
    </tr>
    <tr>
      <td>Updated At</td>
      <td><%= @user.updated_at %></td>
    </tr>
  </tbody>
</table>